DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app varchar(64),
  uri varchar(64),
  ip varchar(15),
  dt timestamp
);
